"""Add password field to user table

Revision ID: 04da513b909a
Revises: 96f80b9e6f8d
Create Date: 2020-07-15 01:03:03.731492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04da513b909a'
down_revision = '96f80b9e6f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
